# Generated by Django 4.0.3 on 2022-04-13 10:07

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('thumbnail', models.ImageField(default='uploads/image/blogThumbnailDefault.png', upload_to='')),
                ('urlBlog', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=250)),
                ('content', froala_editor.fields.FroalaField(blank=True, null=True)),
                ('countViewer', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('STATUS_Pending', 'Pending'), ('STATUS_Approve', 'Approve')], default='STATUS_Pending', max_length=20)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
