# Generated by Django 4.0.3 on 2022-04-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('STATUS_Approve', 'Approve'), ('STATUS_Pending', 'Pending')], default='STATUS_Pending', max_length=20),
        ),
    ]
